networks:
  tracker:
    driver: bridge
    name: tracker


services:
  db:
    image: postgres:15.1-alpine
    restart: always
    env_file:
    - ./receiver/.env
    ports:
    - 5432:5432
    volumes:
    - postgres:/var/lib/postgresql/data
    healthcheck:
      test: [CMD-SHELL, 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -p ${DB_PORT}']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
    - tracker

  nginx:
    container_name: nginx
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    depends_on:
      - workout-data-receiving
    networks:
      - tracker

  workout-data-receiving:
    container_name: workout-data-receiving
    image: workout-data-receiving
    restart: always
    build: 
      context: ./receiver
      dockerfile: Dockerfile
    env_file:
    - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
    - tracker



volumes:
  postgres:
    name: tracker-db-data

    # postgres:
    #   name: fitness-tracker-db-data
  # receiving-logs:
  #   name: fitness-tracker-receiving-logs
  #  processor-logs:
  #   name: fitness-tracker-receiving-logs

