# server {
#     listen 80;
#     server_name localhost;

#     location / {
#         proxy_pass http://processor:8000/;
#     }

#     location / {
#         proxy_pass http://receiver:8000/;
#     }
# }
# server {
#     listen 80;
#     server_name localhost;

#     location / {
#         proxy_pass http://receiver:8000/;
#     }

#     location /processor/ {
#         proxy_pass http://processor:8000/;
#     }
# }

# server {
#     listen 80;
#     server_name localhost;

#     # receiver —  на /
#     location / {
#         proxy_pass http://receiver:8000/;
#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#     }

#     # processor —  на /processor/, сервис видит пути без префикса
#     location /processor/ {
#         proxy_pass http://processor:8000/;
#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#     }
# }